<?php
/**
 * Copyright © StackNuts. All rights reserved.
 * See LICENSE for license details.
 */

declare(strict_types=1);

namespace StackNuts\CloudflareCache\Plugin\Model\Layout;

use Magento\Framework\App\Response\Http as HttpResponse;
use Magento\Framework\View\Layout;
use Psr\Log\LoggerInterface;
use StackNuts\CloudflareCache\Model\Config;

/**
 * When tag-based purging is enabled, mirrors Magento's own X-Magento-Tags
 * header (already generated by Magento_PageCache for any enabled FPC type)
 * into Cloudflare's Cache-Tag response header so Cloudflare's edge can
 * associate the response with those tags for later purge_cache "tags" calls.
 *
 * @see https://developers.cloudflare.com/cache/how-to/purge-cache/purge-by-tags/
 */
class CacheTagHeaderPlugin
{
    /**
     * Cloudflare's soft limit on response header size is ~16KB; leave headroom
     * for the rest of the response headers.
     */
    private const TAG_HEADER_WARNING_LENGTH = 14000;

    public function __construct(
        private readonly HttpResponse $response,
        private readonly Config $config,
        private readonly LoggerInterface $logger
    ) {
    }

    public function afterGetOutput(Layout $subject, string $result): string
    {
        if (!$this->config->isActive() || !$this->config->isTagPurgeMode()) {
            return $result;
        }

        $magentoTagsHeader = $this->response->getHeader('X-Magento-Tags');
        if ($magentoTagsHeader === false) {
            return $result;
        }

        $tags = array_filter(array_map('trim', explode(',', (string)$magentoTagsHeader->getFieldValue())));
        if (!$tags) {
            return $result;
        }

        $tagString = implode(',', array_unique($tags));
        if (strlen($tagString) > self::TAG_HEADER_WARNING_LENGTH) {
            $this->logger->warning('Cache-Tag header is approaching Cloudflare\'s response header size limit.', [
                'length' => strlen($tagString),
            ]);
        }

        $this->response->setHeader('Cache-Tag', $tagString, true);
        if ($this->config->isDebugHeaderEnabled()) {
            $this->response->setHeader('X-Cache-Tags', $tagString, true);
        }

        return $result;
    }
}
